version: "3.9"
services:
  server:
    image: server_dhadkan
    volumes:
      - .:/app
    environment:
      - TESTING=1
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
