# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-21 18:52
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('ques1_a', models.IntegerField()),
                ('ques1_b', models.IntegerField()),
                ('ques1_c', models.IntegerField()),
                ('ques1_d', models.IntegerField()),
                ('ques1_e', models.IntegerField()),
                ('ques1_f', models.IntegerField()),
                ('ques2', models.IntegerField()),
                ('ques3', models.IntegerField()),
                ('ques4', models.IntegerField()),
                ('ques5', models.IntegerField()),
                ('ques6', models.IntegerField()),
                ('ques7', models.IntegerField()),
                ('ques8', models.IntegerField()),
                ('ques9', models.IntegerField()),
                ('ques10', models.IntegerField()),
                ('ques11', models.IntegerField()),
                ('ques12', models.IntegerField()),
                ('ques13', models.IntegerField()),
                ('ques14', models.IntegerField()),
                ('ques15_a', models.IntegerField()),
                ('ques15_b', models.IntegerField()),
                ('ques15_c', models.IntegerField()),
                ('ques15_d', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data2', to='cvd_portal.Patient')),
            ],
        ),
    ]
