# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0002_patientdata2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, max_length=103),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Somesh', max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, max_length=102),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Somesh', max_length=254),
        ),
    ]
