# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata2',
            name='ques10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques15_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques15_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques15_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques15_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_e',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques1_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata2',
            name='ques9',
            field=models.IntegerField(default=0),
        ),
    ]
