# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-25 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0005_auto_20201023_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isBot',
            field=models.BooleanField(default=False),
        ),
    ]
