# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0006_notifications_isbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='isBot',
            field=models.BooleanField(default=True),
        ),
    ]
