# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0007_auto_20201025_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='isBot',
        ),
        migrations.AddField(
            model_name='notifications',
            name='isNOTBot',
            field=models.BooleanField(default=False),
        ),
    ]
