# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-25 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0008_auto_20201025_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
