# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-12-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0009_auto_20201025_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvd_portal.Image'),
        ),
    ]
