# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-25 16:47
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0017_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('repeat', models.BooleanField(default=True)),
                ('frequency', models.FloatField(default=1.0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvd_portal.Patient')),
            ],
        ),
    ]
